---
- yum: name=tar state=present 
  sudo: true
- yum: name=unzip state=present
  sudo: true
- yum: name=openssl-devel  state=present
  sudo: true
- yum: name=zlib-devel  state=present
  sudo: true
- yum: name=gcc  state=present
  sudo: true
- yum: name=gcc-c++  state=present
  sudo: true
- yum: name=make  state=present
  sudo: true
- yum: name=autoconf  state=present
  sudo: true
- yum: name=readline-devel  state=present
  sudo: true
- yum: name=curl-devel  state=present
  sudo: true
- yum: name=expat-devel  state=present
  sudo: true
- yum: name=gettext-devel state=present
  sudo: true